### ISSUE TITLE
Modding issues with Building Type changes

### ISSUE THREAD

**Issue by KABoissonneault** [XJDHDR/DFU_UBLaMF#2] opened 2024-02-26 14:46 UTC
We've hit mod compatibility issues with UBLaMF when Building Type changes are involved. This is a DFU limitation, and I've documented the whole investigation here: https://github.com/Interkarma/daggerfall-unity/issues/2601

In short, if a user's setup ends up with a location's building type and actual building data building type mismatch, DFU breaks down. 
UBLaMF changes FIGHBL00.RMB building0's building type from Temple to Guildhall.
UBLaMF is itself consistent: FIGHBL00.RMB-677-building0 has the type 11 (Guildhall), and all locations using this RMB have a replacement changing a Temple to Guildhall.
Problems arise when a mod changes either one of these locations or this building, without changing the other data type. An example of the former is Fixed Desert Architecture, which changes locations such as location-0-165 (Alik'ra, Alik'r Desert), but does not change FIGHBL00.RMB-677-building0. An example of the latter is Soldier's Luxury Overhaul, which changes the building but none of the locations using it.
For these mods, they either generate their data with changes matching UBLaMF (location or building with type guildhall), or they don't (temple). If they do, users without UBLaMF will have broken locations. If they don't, users with UBLaMF will have broken locations.

Mods have two ways to solve this:
1. Choose whether to force UBLaMF on users, or forbid it. Users wanting to use Fixed Desert Architecture and Soldier's Luxury Overhaul have to make both mod authors to agree on the same choice
2. Provide either UBLaMF files or classic files with their mod, just to ensure the locations and buildings are consistent. The mod wouldn't otherwise modify these files

Neither solutions are great, and require lots of work from mod authors to ensure compatibility on all user setups.

One thing I notice is that UBLaMF changes Temple to Guildhall in FIGHBL00.RMB, but not in FIGHGL00.RMB. Both are "Fighter Trainers" halls with Temple properties, and UBLaMF only "fixes" one. 

This issue is more to open a discussion as to what we want to do to minimize this mess until DFU can be more robust to this problem. 

My suggestion: revert the building type change in FIGHBL00 and its 22 locations until DFU supports this better. This will match the current FIGHGL00 in UBLaMF. DFU 1.1 will have some fixes to ensure these temples play proper music, and otherwise pose no known issues to players other than confusion (they have to search local temples instead of guild halls).
If not, well, you might want to fix FIGHGL00 too, I suppose.

**Comment by XJDHDR** [comment] 2024-02-29 19:39
This is a tough one because, as you said, this is a problem caused by DFU itself and the problem can be resolved by modders integrating my fixes into their work.

The only reason I haven't fixed (not scarequote-fixed) FIGHGL00.RMB is because I didn't know about that one (and yes I will have to rectify that).

What I'm thinking of doing in the short term is splitting UBLaMF into the following parts, where each part will be put in a separate dfmod:

- Meshes & Textures
- Dungeon Block Overrides
- Map Blocks Overrides
- Location & Building Overrides

I will make this split in the next version I release, which should be this or next weekend, given the urgency of this. Finally, until DFU has a fix for this problem, I will also provide a copy of the "Map Block, Location & Building Overrides" dfmod that doesn't include the two Fighter's Guild fixes.

**Comment by KABoissonneault** [comment] 2024-02-29 19:43
Yeah honestly thinking back on it, I might just ask all World Data mods to build their data on top of UBLaMF for now. I know some comments on Reddit are currently asking me to just put all of UBLaMF into DFU because of the houses with broken ceilings... but that's another story

**Closed as completed** 2024-02-29 19:43 UTC

**Comment by XJDHDR** [comment] 2024-02-29 20:23
Do you have any examples of these comments? A quick search didn't reveal anything on my end.

I believe the biggest problem with integrating my mod's changes into the game is that it's difficult to do. For the Block and Location fixes, some code exists for patching the game's BSAs after they're loaded into memory, but before parsing. This requires figuring out the address of the byte(s) in the BSA that needs to be patched. I've only seen Ferital and (I think) Interkarma do this. Meshes (and possibly textures) can be done in the same way, but are I think more difficult, and I've only seen Ferital make such changes.

Edit: As Cabra pointed out, Interkarma also doesn't make a habit of doing this because of [concerns he has](https://discord.com/channels/559842137374457876/650507773389307935/1212538078690938890) of Bethesda dropping the ban hammer if he puts too much of their IP in the project.

Edit2: Actually, I just remembered that it is the models BSA that is patched the way I described. The Block and Location BSAs are actually parsed by DFU (with bugged data), then some code applies specific fixes to the parsed data after that.

**Comment by KABoissonneault** [comment] 2024-02-29 20:40
Started with this thread here.

https://www.reddit.com/r/daggerfallunity/comments/1b2hedm/this_house_has_nothing_of_value/

I'm considering making those houses barred unless they have a WorldData replacement. I mostly have to consider how this would interact with quests.
